Fixed incorrect function calls in open commands
The function open in open_path.py was renamed to open_path at
192876874239617993d007fcbab03f6b888f583f.

Using the incorrect function name caused this error in Windows:
File "OpenProjectPath in C:\...\Sublime Text 3\Installed
Packages\OpenPath.sublime-package", line 6, in run
AttributeError: 'module' object has no attribute 'open'